### ISSUE TITLE
How to register in cpp files?

### ISSUE THREAD

**Issue by engineer1109** [VeriSilicon/vsi-pjrt-plugin#2]
```cpp
class VsiPlugin : public  PjRtPlugin {
public:
       std::string library_path() {}
}; 

RegisterPjRtPlugin("vsi", plugin);
```

This way?

**Comment by Nullkooland** [comment]
The registration logic is implemented by frontend ML frameworks, not part of the plugin itself.
Please refer to https://github.com/pytorch/xla/pull/6360

**Comment by engineer1109** [comment]
Thanks， I know
It gives the function:
void RegisterPjRtPlugin(std::string name,
                        std::shared_ptr<const PjRtPlugin> plugin) 
torch_xla/csrc/runtime/pjrt_registry.cc
