### ISSUE TITLE
The OP list support?

### ISSUE THREAD

**Issue by engineer1109** [VeriSilicon/vsi-pjrt-plugin#3]
I cannot find any OP Support in this code.
How to deal with op support?

**Comment by antkillerfarm** [comment]
We only support the subset of XLA ops, which you can find in:
https://openxla.org/xla/operation_semantics

You can find the op list in:
https://github.com/VeriSilicon/vsi-pjrt-plugin/blob/main/xla/stream_executor/vsi/vsi_graph_builder.h

Such as HandleXXXX, etc

**Comment by engineer1109** [comment]
Looks support 20 - 30 ops. Thanks.
